services:
  - type: web
    name: property-info-system
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start_render.sh
    envVars:
      - key: PORT
        value: 10101
